# Generated by Django 4.0.7 on 2023-12-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbonfiber', '0002_carbondataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carbondataset',
        ),
    ]
