# Generated by Django 4.0.7 on 2023-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonfiber', '0003_delete_carbondataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbondataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mProduct', models.CharField(max_length=50, null=True)),
                ('Netcontent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Netweight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manufactureprocess', models.CharField(max_length=255, null=True)),
                ('RawMaterials', models.CharField(max_length=255, null=True)),
                ('Recyclingprocess', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
