# Generated by Django 4.0.7 on 2024-03-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonfiber', '0004_carbondataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonregister',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
