# Generated by Django 4.0.7 on 2023-12-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsregister',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsregister',
            name='login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsregister',
            name='logout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsregister',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
