# Generated by Django 4.0.7 on 2023-12-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientsregister_approve_clientsregister_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsregister',
            name='clientid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
