# Generated by Django 4.0.7 on 2023-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientsregister_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsregister',
            name='emailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
