# Generated by Django 4.0.7 on 2023-12-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientsregister_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsregister',
            name='fileupload',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
