# Generated by Django 4.0.7 on 2023-12-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_clientsregister_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsregister',
            name='catagory',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
