# Generated by Django 4.0.7 on 2023-12-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientsregister_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientrequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=20, null=True)),
                ('fileupload', models.FileField(default=None, upload_to='documents/')),
                ('catagory', models.CharField(default=None, max_length=50)),
                ('orderid', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
