# Generated by Django 4.0.7 on 2023-12-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequirement',
            name='fileupload',
        ),
        migrations.RemoveField(
            model_name='clientsregister',
            name='fileupload',
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='mProduct',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
