# Generated by Django 4.0.7 on 2023-12-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_clientrequirement_fileupload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsregister',
            name='catagory',
        ),
    ]
