# Generated by Django 4.0.7 on 2023-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_clientsregister_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequirement',
            name='catagory',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
