# Generated by Django 4.0.7 on 2023-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientrequirement_mproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequirement',
            name='Netcontent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='Netweight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='RawMaterials',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='Recyclingprocess',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequirement',
            name='manufactureprocess',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
