# Generated by Django 4.0.7 on 2023-12-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_clientrequirement_netcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequirement',
            name='ghostfishingnets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
