# Generated by Django 4.0.7 on 2023-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientrequirement_ghostfishingnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequirement',
            name='Netcontent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientrequirement',
            name='Netweight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
