# Generated by Django 4.0.7 on 2023-12-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_clientrequirement_netcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequirement',
            name='Netcontent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequirement',
            name='Netweight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequirement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
