# Generated by Django 4.0.7 on 2023-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_clientrequirement_netcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequirement',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
