# Generated by Django 4.0.7 on 2023-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_clientrequirement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequirement',
            name='ghostfishingnets',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
