# Generated by Django 4.0.7 on 2023-12-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_clientrequirement_mprocess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientTrequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=20, null=True)),
                ('catagory', models.CharField(max_length=50, null=True)),
                ('orderid', models.CharField(max_length=20, null=True)),
                ('mProduct', models.CharField(max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('Netcontent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Netweight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('correctionfactor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manufactureprocess', models.CharField(max_length=255, null=True)),
                ('RawMaterials', models.CharField(max_length=255, null=True)),
                ('Recyclingprocess', models.CharField(max_length=255, null=True)),
                ('ghostfishingnets', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('TProcess', models.BooleanField(default=False)),
                ('textilereport', models.BooleanField(default=False)),
            ],
        ),
    ]
