# Generated by Django 4.0.7 on 2024-01-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_clientrequirement_reportapprove_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequirement',
            name='amount',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
