# Generated by Django 4.0.7 on 2024-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_clientrequirement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequirement',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
