# Generated by Django 4.0.7 on 2024-01-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_clientrequirement_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequirement',
            name='finalapprove',
            field=models.BooleanField(default=False),
        ),
    ]
