# Generated by Django 4.0.7 on 2024-03-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_clientsregister_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsregister',
            name='contact',
        ),
        migrations.AddField(
            model_name='clientsregister',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
